name: twopp
description: Simple calculator.
version: 0.0.1
homepage: https://github.com/yuraMovsesyan/twopp

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  graph_dot: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0